[build]
  command = "npm run build:web"
  publish = "dist"

[build.environment]
  EXPO_PUBLIC_API_URL = "https://learnmate-wmt-project.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
